version: '3'
services:
  database:
    image: 'postgres:12' # use latest official postgres version
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=home-sharing-app

    volumes:
      - ../db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ../static-files:/app/uploads # persist data even if container shuts down
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
  server:
    build: ./
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database